using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;

namespace Unary.Core.Analyzers
{
    public class FgdPropertyGenerator : CodeGenerator
    {
        private const string BaseFgdName = "BaseFgd";
        private const string BaseFgdNamespace = "Unary.Core";
        private const string FgdPropertyAttribute = "FgdProperty";

        public override void Generate(SourceProductionContext context, ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
        {
            var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

            if (classSymbol == null)
            {
                return;
            }

            if (!InheritsFromBaseFgd(classSymbol))
            {
                return;
            }

            // Only this class' own [FgdProperty] fields: inherited ones are handled by the base override chain.
            var fields = classSymbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(field => !field.IsStatic
                    && !field.IsImplicitlyDeclared
                    && field.GetAttributes().Any(attribute =>
                        attribute.AttributeClass?.Name == FgdPropertyAttribute
                        || attribute.AttributeClass?.Name == FgdPropertyAttribute + "Attribute"))
                .ToList();

            if (fields.Count == 0)
            {
                return;
            }

            if (!classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                context.ReportDiagnostic(Diagnostic.Create(StaticInfo.CodeGenErrorDescriptor,
                    Location.Create(classDeclaration.SyntaxTree, classDeclaration.Span),
                    "Class with [FgdProperty] fields deriving from BaseFgd has to be partial."));
                return;
            }

            var primaryDeclaration = classSymbol.DeclaringSyntaxReferences.FirstOrDefault();

            if (primaryDeclaration != null &&
                (primaryDeclaration.SyntaxTree != classDeclaration.SyntaxTree ||
                primaryDeclaration.Span != classDeclaration.Span))
            {
                return;
            }

            var namespaceName = GetNamespace(classDeclaration);
            var className = classDeclaration.Identifier.Text;
            var hintName = string.IsNullOrEmpty(namespaceName) ? className : $"{namespaceName}.{className}";

            var sourceText = GenerateApplyProperties(namespaceName, className, fields);
            context.AddSource($"{hintName}.FgdApplyProperties.g.cs", SourceText.From(sourceText, System.Text.Encoding.UTF8));
        }

        private static bool InheritsFromBaseFgd(INamedTypeSymbol symbol)
        {
            for (var current = symbol.BaseType; current != null; current = current.BaseType)
            {
                if (current.Name == BaseFgdName
                    && current.ContainingNamespace?.ToDisplayString() == BaseFgdNamespace)
                {
                    return true;
                }
            }

            return false;
        }

        private static string GenerateApplyProperties(string namespaceName, string className, List<IFieldSymbol> fields)
        {
            var sb = new System.Text.StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Godot;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        public override void ApplyProperties(global::Godot.Collections.Dictionary properties)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.ApplyProperties(properties);");

            foreach (var field in fields)
            {
                var typeName = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var local = $"{field.Name}Variant";

                string assignment = field.Type.TypeKind == TypeKind.Enum
                    ? $"({typeName}){local}.As<long>()"
                    : $"{local}.As<{typeName}>()";

                sb.AppendLine();
                sb.AppendLine($"            if (properties.TryGetValue(\"{field.Name}\", out global::Godot.Variant {local}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                {field.Name} = {assignment};");
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }
    }
}
