// Copyright (c) 2023 func-godot
// C# port of func_godot (https://github.com/func-godot/func_godot_plugin),
// used under the MIT License. See addons/unary.core.editor/sources/func_godot/LICENSE.md.

using Godot;
using System;
using System.Collections.Generic;

namespace FuncGodot
{
    /// <summary>
    /// Builds a scene from a Valve 220 Quake .map file, according to its <see cref="FuncGodotMapSettings"/>
    /// and the <see cref="FuncGodotFGDFile"/> that settings resource points at.
    /// </summary>
    [Tool]
    [GlobalClass]
    public partial class FuncGodotMap : Node3D
    {
        public const string Signature = "[MAP]";

        public FuncGodotMap()
        {
            // A new map node defaults its settings to the shared config's DefaultMapSettings, so it comes
            // pre-wired like func_godot does. A saved scene's stored MapSettings overrides this afterward.
            FuncGodotConfig config = FuncGodotConfig.Load();

            if (config?.DefaultMapSettings != null)
            {
                MapSettings = config.DefaultMapSettings;
            }
        }

        [Flags]
        public enum BuildFlagBits
        {
            None = 0,

            /// Unwrap UV2s during geometry generation, for lightmap baking.
            UnwrapUv2 = 1 << 0,

            /// Print each build step as it completes.
            ShowProfileInfo = 1 << 1,

            /// Skip vertex normal smoothing regardless of what entities ask for.
            DisableSmoothing = 1 << 2,
        }

        [Signal]
        public delegate void BuildFailedEventHandler();

        [Signal]
        public delegate void BuildCompleteEventHandler();

        [ExportToolButton("Build Map", Icon = "CollisionShape3D")]
        public Callable BuildMapButton => Callable.From(Build);

        [ExportToolButton("Clear Map", Icon = "Skeleton3D")]
        public Callable ClearMapButton => Callable.From(ClearChildren);

        [ExportCategory("Map")]

        /// Local path to the .map file to build.
        [Export(PropertyHint.File, "*.map")]
        public string LocalMapFile = string.Empty;

        /// Global path to the .map file to build. Overrides <see cref="LocalMapFile"/>.
        [Export(PropertyHint.GlobalFile, "*.map")]
        public string GlobalMapFile = string.Empty;

        /// Build scale, texture locations, entity definitions, and more.
        [Export]
        public FuncGodotMapSettings MapSettings;

        [ExportCategory("Build")]

        [Export(PropertyHint.Flags, "Unwrap UV2:1,Show Profiling Info:2,Disable Smooth Shading:4")]
        public BuildFlagBits BuildFlags = BuildFlagBits.None;

        /// <summary>
        /// Every face is cut out of a plane this size, like a sculptor's block of marble. It must be large
        /// enough to cover the map, but smaller values reduce the floating point error that opens seams
        /// between polygons. Measured in Godot units, not Quake units.
        /// </summary>
        [Export(PropertyHint.Range, "256.0,2048.0,128.0")]
        public float HyperplaneSize = 512.0f;

        // Resolved from the local and global paths, so both are supported at runtime.
        private string _mapFile = string.Empty;

        private void FailBuild(string reason, bool notify = false)
        {
            GD.PushError(Signature + " " + reason);

            if (notify)
            {
                EmitSignal(SignalName.BuildFailed);
            }
        }

        /// <summary>
        /// Frees every child of the map node. This does not distinguish nodes generated by a build from ones
        /// you added yourself.
        /// </summary>
        public void ClearChildren()
        {
            foreach (Node child in GetChildren())
            {
                RemoveChild(child);
                child.QueueFree();
            }

            if (Engine.Singleton.IsEditorHint())
            {
                EditorInterface.Singleton.MarkSceneAsUnsaved();
            }
        }

        /// Checks that a map file was provided and can be found.
        public Error Verify()
        {
            // The global path wins, so a build can be driven from an absolute path at runtime.
            _mapFile = string.IsNullOrEmpty(GlobalMapFile) ? LocalMapFile : GlobalMapFile;

            if (string.IsNullOrEmpty(_mapFile))
            {
                FailBuild("Cannot build empty map file.");
                return Error.InvalidParameter;
            }

            if (_mapFile.StartsWith("uid://"))
            {
                long uid = ResourceUid.TextToId(_mapFile);

                if (!ResourceUid.HasId(uid))
                {
                    FailBuild($"Failed to retrieve path for UID ({_mapFile})");
                    return Error.DoesNotExist;
                }

                _mapFile = ResourceUid.GetIdPath(uid);
            }

            // In an exported project the .map is gone and only the imported resource remains.
            if (!FileAccess.FileExists(_mapFile) && !ResourceLoader.Exists(_mapFile))
            {
                FailBuild($"Map file {_mapFile} does not exist.");
                return Error.DoesNotExist;
            }

            return Error.Ok;
        }

        /// <summary>
        /// Clears the map node, then parses the map file, generates its geometry, and assembles its entities
        /// into the SceneTree.
        /// </summary>
        public void Build()
        {
            ulong startTime = Time.GetTicksMsec();

            bool profile = BuildFlags.HasFlag(BuildFlagBits.ShowProfileInfo);

            if (profile)
            {
                FuncGodotUtil.PrintProfileInfo("Building...", Signature);
            }

            ClearChildren();

            Error verifyError = Verify();

            if (verifyError != Error.Ok)
            {
                FailBuild($"Verification failed: {verifyError}. Aborting map build", true);
                return;
            }

            if (MapSettings == null)
            {
                FailBuild("Map node has no map settings. Aborting map build", true);
                return;
            }

            if (MapSettings.EntityFgd == null)
            {
                FailBuild("Map settings have no entity FGD. Aborting map build", true);
                return;
            }

            FuncGodotParser parser = new();

            if (profile)
            {
                GD.Print("\nPARSER");
                parser.DeclareStep += step => FuncGodotUtil.PrintProfileInfo(step, FuncGodotParser.Signature);
            }

            FuncGodotData.ParseData parseData = parser.ParseMapData(_mapFile, MapSettings);

            if (parseData.Entities.Count == 0)
            {
                // The parser already reported why.
                EmitSignal(SignalName.BuildFailed);
                return;
            }

            List<FuncGodotData.EntityData> entities = parseData.Entities;
            List<FuncGodotData.GroupData> groups = parseData.Groups;

            FuncGodotGeometryGenerator generator = new(MapSettings, HyperplaneSize);

            if (profile)
            {
                GD.Print("\nGEOMETRY GENERATOR");
                generator.DeclareStep += step => FuncGodotUtil.PrintProfileInfo(step, FuncGodotGeometryGenerator.Signature);
            }

            Error generateError = generator.Build(BuildFlags, entities);

            if (generateError != Error.Ok)
            {
                FailBuild($"Geometry generation failed: {generateError}", true);
                return;
            }

            FuncGodotEntityAssembler assembler = new(MapSettings);

            if (profile)
            {
                GD.Print("\nENTITY ASSEMBLER");
                assembler.DeclareStep += step => FuncGodotUtil.PrintProfileInfo(step, FuncGodotEntityAssembler.Signature);
            }

            assembler.Build(this, entities, groups);

            if (profile)
            {
                double elapsed = (Time.GetTicksMsec() - startTime) / 1000.0;
                GD.Print($"\nCompleted in {elapsed} seconds\n");
                FuncGodotUtil.PrintProfileInfo("Build complete", Signature);
            }

            if (Engine.Singleton.IsEditorHint())
            {
                EditorInterface.Singleton.MarkSceneAsUnsaved();
            }

            EmitSignal(SignalName.BuildComplete);
        }
    }
}
